BROKER_URL:  broker
BROKER_PORT: 1883
#CA_CERT: cert.pem
TOPIC: site1/
QOS: ${QOS}
NR_OF_MESSAGES: 1000
PUBLISH_INTERVAL: 1
TLS_ENABLED: False
CLEAN_START: True
RETAIN: False
REATTEMPTS: 0
KEEPALIVE: 60
TESTDATA_PATH: /app/data/provider1
CLIENT_ID: provider1
